apiVersion: v1
kind: ConfigMap

metadata:
  name: hrms-api-config

data:
  SPRING_APPLICATION_NAME: hrms-api

  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrms

  SPRING_DATASOURCE_USERNAME: hrmsuser

  SERVER_PORT: "8081"

  SPRING_PROFILES_ACTIVE: dev

  LOGGING_LEVEL_ROOT: INFO