apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Netherlands!289
  MYSQL_DATABASE: hrms
  MYSQL_USER: hrmsuser
  MYSQL_PASSWORD: Netherlands!289